blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/calambrenet/forky/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: Ideas & Suggestions
    url: https://github.com/calambrenet/forky/discussions/categories/ideas
    about: Share ideas and discuss potential features
